### ISSUE TITLE
Enable travisCI pull request integration

### ISSUE THREAD

**Issue by toabctl** [openSUSE/obs-service-set_version#13]
After https://github.com/openSUSE/obs-service-set_version/pull/12 was merged, PR integration in TravisCI must be enabled. I think it can be done here: https://travis-ci.org/openSUSE/obs-service-set_version/ . @adrianschroeter can you do that, please?

**Comment by adrianschroeter** [comment]
a bit more complicated, but done now.

python 2.6 test is failing: https://travis-ci.org/openSUSE/obs-service-set_version
