### ISSUE TITLE
[BUG] Generated "version" field contains newline?

### ISSUE THREAD

**Issue by martinrotter** [openSUSE/obs-service-set_version#26]
This concerns dsc and spec files.

See [this](https://build.opensuse.org/package/view_file/home:skunkos:rssguard/rssguard-qt5/_service:set_version:rssguard-qt5.dsc?expand=1).

**Comment by toabctl** [comment]
I think this will be fixed with https://github.com/openSUSE/obs-service-set_version/pull/23 .

**Comment by adrianschroeter** [comment]
is it fixed for you meanwhile?

**Comment by martinrotter** [comment]
Yes, seems fixed to me.
