### ISSUE TITLE
Update version in Debtransform lines.

### ISSUE THREAD

**Issue by hurricanehrndz** [openSUSE/obs-service-set_version#29]
_replace_tag function only Updates the Version tag line (i.e. Version:) 

set_version service should update the version numbers in debtransfrom-tar lines.

For example:

```
Debtransform-Tar: package-%version.tar.gz  
Debtransform-Tar: package-$version.tar.gz 
```

Should have %version or $version updated to the actual version from any previous services.

**Comment by hurricanehrndz** [comment]
nm, issue is with recompress service.

**Comment by noscript** [comment]
`DEBTRANSFORM-TAR` is pretty much useless when used together with `tar_scm`, as the resulting tarball is always going to have some part of the filename set dynamically, which is actually important for `set_version` to work.

Being able to access version information `DEBTRANSFORM-TAR` is a must-have.

**Comment by jjacque** [comment]
Hi, i guess `DEBTRANSFORM-TAR` is not useless when your sources contain multiple archives (ie `vendor.tar.gz` generated by `obs-service-go_modules`).
I did a patch to be able to use:
`Debtransform-Tar: archive-prefix-${Version}.tar.gz` and have it modified by `set_version`.
Here it is, even if i confess it's a pretty naive implem.

```
diff -ru a/set_version b/set_version
--- a/set_version	2019-11-03 22:54:25.000000000 +0100
+++ b/set_version	2019-11-05 22:49:16.813779064 +0100
@@ -281,6 +281,24 @@
             f.write(contents_new)
 
 
+def _replace_dsc_debtransform(filename, string):
+    with codecs.open(filename, 'r+', 'utf8') as f:
+        contents = f.read()
+        f.seek(0)
+        tag = 'Debtransform-Tar'
+        contents_new, subs = re.subn(
+            r'^{tag}:([ \t\f\v]*)([-\w\.]*)\${{Version}}([-\w\.]*)'.format(
+                tag=tag),
+            r'{tag}:\g<1>\g<2>{string}\g<3>'.format(
+                tag=tag, string=string),
+            contents, flags=re.MULTILINE)
+        if DEBUG:
+            print("dsc debtransform updated: ", contents_new)
+        if subs > 0:
+            f.truncate()
+            f.write(contents_new)
+
+
 def _replace_debian_changelog_version(fname, version_new):
     # first, modify a copy of filename and then move it
     # get current version
@@ -405,6 +423,7 @@
             _replace_tag(filename, 'Version', version + "-0")
         else:
             _replace_tag(filename, 'Version', version)
+            _replace_dsc_debtransform(filename, version)
 
     for f in filter(lambda x: x.endswith(("debian.changelog")), files):
         filename = outdir + "/" + f
```
