### ISSUE TITLE
Missing license content

### ISSUE THREAD

**Issue by Conan-Kudo** [openSUSE/obs-service-set_version#57]
This source service is labeled as `GPL-2.0+` in the packaging, but there's no license file for the GPLv2, nor is the requisite header in the source files present. Can this be fixed, please?

This is necessary for me to package this source service in Fedora.

**Comment by seife** [comment]
https://github.com/openSUSE/obs-service-set_version/blob/master/set_version#L9

**Comment by Conan-Kudo** [comment]
So then this one just needs a license file. :)

**Comment by adrianschroeter** [comment]
added
